version: "3.8"

services: 
  nginx:                      # name of the container ( --name nginx )
    image: nginx:1.23.3       # image to build the container
    ports: 
      - '80:80'               # Port mapping ( -p 80:80 )
    volumes: 
      - ./www:/var/www/html   # Bind-mount
      - ./nginx/conf.d:/etc/nginx/conf.d/
    
    depends_on:     # build this contain after container "php" is built
      - php
    
  php:
    build:   # Tell docker where to find the dockerfile to build the image
      context: ./www
      dockerfile: php.dockerfile
    
    ports: 
      - '9000:9000'
    
    volumes:
      - ./www:/var/www/html
      - ./mysql/mysql_sock:/var/run/mysqld 
    
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.31

    ports: 
      - '33267:3306'

    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d 
      - ./mysql/mysql_sock:/var/run/mysqld 

    environment:
      - MYSQL_ROOT_PASSWORD=123456

    depends_on:
      - php
    
  vuejs:

    build:
      context: ./vuejs
      dockerfile: vue.dockerfile

    ports: 
      - '8080:80'

    depends_on:
      - nginx
      - php
      - mysql
    